@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.accessToken}}

@refreshToken = {{authenticate.response.body.refreshToken}}

# RECADOS

### findAll

# @name findAll
GET {{baseUrl}}/recados/
?limit=10
&offset=10


### findOne

# @name findOne
GET {{baseUrl}}/recados/9
Authorization: Bearer 123

### createOne

# @name createOne
POST {{baseUrl}}/recados
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "texto": "Este é um recado novo recado para testes 2",
  "paraId": 10
}


### updateOne

# @name updateOne
PATCH  {{baseUrl}}/recados/17
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "texto": "Este é um recado atualizado",
  "lido": true
}


### deleteOne

# @name deleteOne
DELETE {{baseUrl}}/recados/6
Authorization: Bearer {{authToken}}

# Pessoas

### Lista todas as pessoas
GET {{baseUrl}}/pessoas/
?limit=10
&offset=0
Authorization: Bearer {{authToken}}

### Lista uma pessoa
GET {{baseUrl}}/pessoas/11
Authorization: Bearer {{authToken}}

### Cria uma pessoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
  "email": "rafael@email.com",
  "password": "rafael",
  "nome": "rafael"
}

### Atualiza uma pessoa
PATCH {{baseUrl}}/pessoas/11
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "password": "rafael"
}

### Apaga uma pessoa
DELETE {{baseUrl}}/pessoas/1
Authorization: Bearer {{authToken}}

### AUTH

### Faz login
# @name authenticate
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "email": "rafael@email.com",
  "password": "rafael"
}

### Re-Autenticação
POST {{baseUrl}}/auth/refresh/
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}


# Upload
### Foto da pessoa
POST {{baseUrl}}/pessoas/upload-picture/
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=----BoundaryDelimitadorHttp

------BoundaryDelimitadorHttp
Content-Disposition: form-data; name="file"; filename="fff.png"
Content-Type: image/png

< ./dev/images/fff.png
------BoundaryDelimitadorHttp--