@baseUrl = http://localhost:3000

# RECADOS

### findAll

# @name findAll
GET {{baseUrl}}/recados/
?limit=10
&offset=5


### findOne

# @name findOne
GET {{baseUrl}}/recados/9
Authorization: Bearer 123

### createOne

# @name createOne
POST {{baseUrl}}/recados
Content-Type: application/json

{
  "texto": "Este é um recado novo recado para testes 2",
  "deId": 6,
  "paraId": 10
}


### updateOne

# @name updateOne
PATCH  {{baseUrl}}/recados/9
Content-Type: application/json

{
  "texto": "Este é um recado atualizado",
  "lido": true
}


### deleteOne

# @name deleteOne
DELETE {{baseUrl}}/recados/2

# Pessoas

### Lista todas as pessoas
GET {{baseUrl}}/pessoas/
?limit=10
&offset=0

### Lista uma pessoa
GET {{baseUrl}}/pessoas/6

### Cria uma pessoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
  "email": "root@email.com",
  "password": "root",
  "nome": "root"
}

### Atualiza uma pessoa
PATCH {{baseUrl}}/pessoas/6
Content-Type: application/json

{
  "password": "123456",
  "nome": "ADMIN"
}

### Apaga uma pessoa
DELETE {{baseUrl}}/pessoas/1


